//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculateVessels.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalculateVessels.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Bolt {
            get {
                object obj = ResourceManager.GetObject("Bolt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BoltGroove {
            get {
                object obj = ResourceManager.GetObject("BoltGroove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BSphRadial {
            get {
                object obj = ResourceManager.GetObject("BSphRadial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BSphRadialDekart {
            get {
                object obj = ResourceManager.GetObject("BSphRadialDekart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BSphTilted {
            get {
                object obj = ResourceManager.GetObject("BSphTilted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BSphTiltedDekart {
            get {
                object obj = ResourceManager.GetObject("BSphTiltedDekart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BSphVert {
            get {
                object obj = ResourceManager.GetObject("BSphVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] BSphVertDekart {
            get {
                object obj = ResourceManager.GetObject("BSphVertDekart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Cil {
            get {
                object obj = ResourceManager.GetObject("Cil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeAxial {
            get {
                object obj = ResourceManager.GetObject("ConeAxial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeElemBottom {
            get {
                object obj = ResourceManager.GetObject("ConeElemBottom", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeElemLeft {
            get {
                object obj = ResourceManager.GetObject("ConeElemLeft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeElemRight {
            get {
                object obj = ResourceManager.GetObject("ConeElemRight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeElemTop {
            get {
                object obj = ResourceManager.GetObject("ConeElemTop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeOffset {
            get {
                object obj = ResourceManager.GetObject("ConeOffset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeRadial {
            get {
                object obj = ResourceManager.GetObject("ConeRadial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeSteepAxial {
            get {
                object obj = ResourceManager.GetObject("ConeSteepAxial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeSteepOffset {
            get {
                object obj = ResourceManager.GetObject("ConeSteepOffset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeSteepRadial {
            get {
                object obj = ResourceManager.GetObject("ConeSteepRadial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeSteepTilted {
            get {
                object obj = ResourceManager.GetObject("ConeSteepTilted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeSteepVert {
            get {
                object obj = ResourceManager.GetObject("ConeSteepVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeTilted {
            get {
                object obj = ResourceManager.GetObject("ConeTilted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConeVert {
            get {
                object obj = ResourceManager.GetObject("ConeVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CylAxial {
            get {
                object obj = ResourceManager.GetObject("CylAxial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CylOffset {
            get {
                object obj = ResourceManager.GetObject("CylOffset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CylRadial {
            get {
                object obj = ResourceManager.GetObject("CylRadial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CylTilted {
            get {
                object obj = ResourceManager.GetObject("CylTilted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Ell {
            get {
                object obj = ResourceManager.GetObject("Ell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EllRadial {
            get {
                object obj = ResourceManager.GetObject("EllRadial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EllRadialDekart {
            get {
                object obj = ResourceManager.GetObject("EllRadialDekart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EllTilted {
            get {
                object obj = ResourceManager.GetObject("EllTilted", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EllTiltedDekart {
            get {
                object obj = ResourceManager.GetObject("EllTiltedDekart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EllVert {
            get {
                object obj = ResourceManager.GetObject("EllVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] EllVertDekart {
            get {
                object obj = ResourceManager.GetObject("EllVertDekart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl1_a {
            get {
                object obj = ResourceManager.GetObject("fl1_a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl1_a52857 {
            get {
                object obj = ResourceManager.GetObject("fl1_a52857", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl1_b {
            get {
                object obj = ResourceManager.GetObject("fl1_b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl1_b52857 {
            get {
                object obj = ResourceManager.GetObject("fl1_b52857", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl1_c {
            get {
                object obj = ResourceManager.GetObject("fl1_c", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl1_c52857 {
            get {
                object obj = ResourceManager.GetObject("fl1_c52857", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl1_d {
            get {
                object obj = ResourceManager.GetObject("fl1_d", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl1_d52857 {
            get {
                object obj = ResourceManager.GetObject("fl1_d52857", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl2_a {
            get {
                object obj = ResourceManager.GetObject("fl2_a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl2_a52857 {
            get {
                object obj = ResourceManager.GetObject("fl2_a52857", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl2_b {
            get {
                object obj = ResourceManager.GetObject("fl2_b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl2_b52857 {
            get {
                object obj = ResourceManager.GetObject("fl2_b52857", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl2_c {
            get {
                object obj = ResourceManager.GetObject("fl2_c", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl2_c52857 {
            get {
                object obj = ResourceManager.GetObject("fl2_c52857", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] fl5_a {
            get {
                object obj = ResourceManager.GetObject("fl5_a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FlatBottomWithMoment {
            get {
                object obj = ResourceManager.GetObject("FlatBottomWithMoment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FlatBottomWithMomentWithGroove {
            get {
                object obj = ResourceManager.GetObject("FlatBottomWithMomentWithGroove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FlatRadial {
            get {
                object obj = ResourceManager.GetObject("FlatRadial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FlatRadialDekart {
            get {
                object obj = ResourceManager.GetObject("FlatRadialDekart", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСТ 34233.1-2017 Сосуды и аппараты. Нормы и методы расчета на прочность. Общие требования.
        /// </summary>
        public static string GOST_34233_1 {
            get {
                return ResourceManager.GetString("GOST_34233_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСТ 34233.10-2017 Сосуды и аппараты. Нормы и методы расчета на прочность. Сосуды и аппараты работающие с сероводородными средами.
        /// </summary>
        public static string GOST_34233_10 {
            get {
                return ResourceManager.GetString("GOST_34233_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСТ 34233.11-2017 Сосуды и аппараты. Нормы и методы расчета на прочность. Метод расчета на прочность обечаек и днищ с учетом смещения кромок сварных соединений, угловатости и некруглости обечаек.
        /// </summary>
        public static string GOST_34233_11 {
            get {
                return ResourceManager.GetString("GOST_34233_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСТ 34233.2-2017 Сосуды и аппараты. Нормы и методы расчета на прочность. Расчет цилиндрических и конических обечаек, выпуклых и плоских днищ и крышек.
        /// </summary>
        public static string GOST_34233_2 {
            get {
                return ResourceManager.GetString("GOST_34233_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСТ 34233.3-2017 Сосуды и аппараты. Нормы и методы расчета на прочность. Укрепление отверстий в обечайках и днищах при внутреннем и наружном давлениях. Расчет на прочность обечаек и днищ при внешних статических нагрузках на штуцер.
        /// </summary>
        public static string GOST_34233_3 {
            get {
                return ResourceManager.GetString("GOST_34233_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСТ 34233.4-2017 Сосуды и аппараты. Нормы и методы расчета на прочность. Расчет на прочность и герметичность фланцевых соединений.
        /// </summary>
        public static string GOST_34233_4 {
            get {
                return ResourceManager.GetString("GOST_34233_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСТ 34233.5-2017 Сосуды и аппараты. Нормы и методы расчета на прочность. Расчет  обечаек и днищ от воздействия опорных нагрузок.
        /// </summary>
        public static string GOST_34233_5 {
            get {
                return ResourceManager.GetString("GOST_34233_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСТ 34233.6-2017 Сосуды и аппараты. Нормы и методы расчета на прочность. Расчет на прочность при малоцикловых нагрузках.
        /// </summary>
        public static string GOST_34233_6 {
            get {
                return ResourceManager.GetString("GOST_34233_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСТ 34233.7-2017 Сосуды и аппараты. Нормы и методы расчета на прочность. Теплообменные аппараты.
        /// </summary>
        public static string GOST_34233_7 {
            get {
                return ResourceManager.GetString("GOST_34233_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСТ 34233.8-2017 Сосуды и аппараты. Нормы и методы расчета на прочность. Сосуды и аппараты с рубашками.
        /// </summary>
        public static string GOST_34233_8 {
            get {
                return ResourceManager.GetString("GOST_34233_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ГОСТ 34233.9-2017 Сосуды и аппараты. Нормы и методы расчета на прочность. Аппараты колонного типа.
        /// </summary>
        public static string GOST_34233_9 {
            get {
                return ResourceManager.GetString("GOST_34233_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon1000 {
            get {
                object obj = ResourceManager.GetObject("Icon1000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon10000 {
            get {
                object obj = ResourceManager.GetObject("Icon10000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon10100 {
            get {
                object obj = ResourceManager.GetObject("Icon10100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon111000 {
            get {
                object obj = ResourceManager.GetObject("Icon111000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon112000 {
            get {
                object obj = ResourceManager.GetObject("Icon112000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon12000 {
            get {
                object obj = ResourceManager.GetObject("Icon12000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon15000 {
            get {
                object obj = ResourceManager.GetObject("Icon15000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon16000 {
            get {
                object obj = ResourceManager.GetObject("Icon16000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon17000 {
            get {
                object obj = ResourceManager.GetObject("Icon17000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon18000 {
            get {
                object obj = ResourceManager.GetObject("Icon18000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon18500 {
            get {
                object obj = ResourceManager.GetObject("Icon18500", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon2000 {
            get {
                object obj = ResourceManager.GetObject("Icon2000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon20000 {
            get {
                object obj = ResourceManager.GetObject("Icon20000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon21000 {
            get {
                object obj = ResourceManager.GetObject("Icon21000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon21200 {
            get {
                object obj = ResourceManager.GetObject("Icon21200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon21400 {
            get {
                object obj = ResourceManager.GetObject("Icon21400", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon22000 {
            get {
                object obj = ResourceManager.GetObject("Icon22000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon22100 {
            get {
                object obj = ResourceManager.GetObject("Icon22100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon22200 {
            get {
                object obj = ResourceManager.GetObject("Icon22200", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon23000 {
            get {
                object obj = ResourceManager.GetObject("Icon23000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon25000 {
            get {
                object obj = ResourceManager.GetObject("Icon25000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon26000 {
            get {
                object obj = ResourceManager.GetObject("Icon26000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon27000 {
            get {
                object obj = ResourceManager.GetObject("Icon27000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon28000 {
            get {
                object obj = ResourceManager.GetObject("Icon28000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon28300 {
            get {
                object obj = ResourceManager.GetObject("Icon28300", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon29000 {
            get {
                object obj = ResourceManager.GetObject("Icon29000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon3000 {
            get {
                object obj = ResourceManager.GetObject("Icon3000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon31000 {
            get {
                object obj = ResourceManager.GetObject("Icon31000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon32000 {
            get {
                object obj = ResourceManager.GetObject("Icon32000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon36000 {
            get {
                object obj = ResourceManager.GetObject("Icon36000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon37000 {
            get {
                object obj = ResourceManager.GetObject("Icon37000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon37500 {
            get {
                object obj = ResourceManager.GetObject("Icon37500", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon38000 {
            get {
                object obj = ResourceManager.GetObject("Icon38000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon38500 {
            get {
                object obj = ResourceManager.GetObject("Icon38500", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon38600 {
            get {
                object obj = ResourceManager.GetObject("Icon38600", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon39000 {
            get {
                object obj = ResourceManager.GetObject("Icon39000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon39500 {
            get {
                object obj = ResourceManager.GetObject("Icon39500", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon4000 {
            get {
                object obj = ResourceManager.GetObject("Icon4000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon40000 {
            get {
                object obj = ResourceManager.GetObject("Icon40000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon40500 {
            get {
                object obj = ResourceManager.GetObject("Icon40500", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon41000 {
            get {
                object obj = ResourceManager.GetObject("Icon41000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon42000 {
            get {
                object obj = ResourceManager.GetObject("Icon42000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon43000 {
            get {
                object obj = ResourceManager.GetObject("Icon43000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon44000 {
            get {
                object obj = ResourceManager.GetObject("Icon44000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon45000 {
            get {
                object obj = ResourceManager.GetObject("Icon45000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon46000 {
            get {
                object obj = ResourceManager.GetObject("Icon46000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon5000 {
            get {
                object obj = ResourceManager.GetObject("icon5000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon50100 {
            get {
                object obj = ResourceManager.GetObject("Icon50100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon6000 {
            get {
                object obj = ResourceManager.GetObject("Icon6000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon7000 {
            get {
                object obj = ResourceManager.GetObject("Icon7000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon70000 {
            get {
                object obj = ResourceManager.GetObject("Icon70000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon71000 {
            get {
                object obj = ResourceManager.GetObject("Icon71000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon72000 {
            get {
                object obj = ResourceManager.GetObject("Icon72000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon73000 {
            get {
                object obj = ResourceManager.GetObject("Icon73000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon75000 {
            get {
                object obj = ResourceManager.GetObject("Icon75000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon76000 {
            get {
                object obj = ResourceManager.GetObject("Icon76000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon76500 {
            get {
                object obj = ResourceManager.GetObject("Icon76500", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon77000 {
            get {
                object obj = ResourceManager.GetObject("Icon77000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon78000 {
            get {
                object obj = ResourceManager.GetObject("Icon78000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon8000 {
            get {
                object obj = ResourceManager.GetObject("Icon8000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon8100 {
            get {
                object obj = ResourceManager.GetObject("Icon8100", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon81000 {
            get {
                object obj = ResourceManager.GetObject("Icon81000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon83000 {
            get {
                object obj = ResourceManager.GetObject("Icon83000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon87000 {
            get {
                object obj = ResourceManager.GetObject("Icon87000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon88000 {
            get {
                object obj = ResourceManager.GetObject("Icon88000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon9000 {
            get {
                object obj = ResourceManager.GetObject("Icon9000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon92000 {
            get {
                object obj = ResourceManager.GetObject("Icon92000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon9500 {
            get {
                object obj = ResourceManager.GetObject("Icon9500", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Icon98000 {
            get {
                object obj = ResourceManager.GetObject("Icon98000", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Nozzle1 {
            get {
                object obj = ResourceManager.GetObject("Nozzle1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Nozzle2 {
            get {
                object obj = ResourceManager.GetObject("Nozzle2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Nozzle3 {
            get {
                object obj = ResourceManager.GetObject("Nozzle3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Nozzle4 {
            get {
                object obj = ResourceManager.GetObject("Nozzle4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Nozzle5 {
            get {
                object obj = ResourceManager.GetObject("Nozzle5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Nozzle6 {
            get {
                object obj = ResourceManager.GetObject("Nozzle6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Nozzle7 {
            get {
                object obj = ResourceManager.GetObject("Nozzle7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Nozzle8 {
            get {
                object obj = ResourceManager.GetObject("Nozzle8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PC1 {
            get {
                object obj = ResourceManager.GetObject("PC1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PC2 {
            get {
                object obj = ResourceManager.GetObject("PC2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PC3 {
            get {
                object obj = ResourceManager.GetObject("PC3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PC4 {
            get {
                object obj = ResourceManager.GetObject("PC4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PC5 {
            get {
                object obj = ResourceManager.GetObject("PC5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PC6 {
            get {
                object obj = ResourceManager.GetObject("PC6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PC7 {
            get {
                object obj = ResourceManager.GetObject("PC7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pldn1 {
            get {
                object obj = ResourceManager.GetObject("pldn1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pldn10 {
            get {
                object obj = ResourceManager.GetObject("pldn10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pldn11 {
            get {
                object obj = ResourceManager.GetObject("pldn11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pldn12 {
            get {
                object obj = ResourceManager.GetObject("pldn12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pldn13 {
            get {
                object obj = ResourceManager.GetObject("pldn13", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pldn2 {
            get {
                object obj = ResourceManager.GetObject("pldn2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pldn3 {
            get {
                object obj = ResourceManager.GetObject("pldn3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pldn4 {
            get {
                object obj = ResourceManager.GetObject("pldn4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pldn5 {
            get {
                object obj = ResourceManager.GetObject("pldn5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pldn6 {
            get {
                object obj = ResourceManager.GetObject("pldn6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pldn7 {
            get {
                object obj = ResourceManager.GetObject("pldn7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pldn8 {
            get {
                object obj = ResourceManager.GetObject("pldn8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] pldn9 {
            get {
                object obj = ResourceManager.GetObject("pldn9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SaddleNothingElem {
            get {
                object obj = ResourceManager.GetObject("SaddleNothingElem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SaddleRingInElem {
            get {
                object obj = ResourceManager.GetObject("SaddleRingInElem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SaddleRingOutElem {
            get {
                object obj = ResourceManager.GetObject("SaddleRingOutElem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SaddleRingRib1Elem {
            get {
                object obj = ResourceManager.GetObject("SaddleRingRib1Elem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SaddleRingRib3Elem {
            get {
                object obj = ResourceManager.GetObject("SaddleRingRib3Elem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SaddleSheetElem {
            get {
                object obj = ResourceManager.GetObject("SaddleSheetElem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Sfer {
            get {
                object obj = ResourceManager.GetObject("Sfer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Stud {
            get {
                object obj = ResourceManager.GetObject("Stud", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] StudGroove {
            get {
                object obj = ResourceManager.GetObject("StudGroove", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
